version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt 
      - run:
          name: Run unit tests
          command: python -m unittest unit_tests.py
      - run:
          name: Run integration tests
          command: python -m unittest integration_tests.py